services:
  - type: web
    name: telegram-ads-bot
    runtime: python
    buildCommand: ""
    startCommand: gunicorn main:app --worker-class gthread --threads 4 --bind 0.0.0.0:$PORT
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: FB_ACCESS_TOKEN
        sync: false
